export const Categories = [
  'Celulares y Smartphones',
  'Televisores',
  'Cámaras y Accesorios',
  'Audio y Sonido',
  'Computadoras y Laptops',
  'Muebles',
  'Electrodomésticos',
  'Decoración',
  'Iluminación',
  'Jardinería',
  'Ropa',
  'Zapatos',
  'Zapatillas',
  'Bolsos y Accesorios',
  'Relojes',
  'Joyas',
  'Equipamiento Deportivo',
  'Ropa Deportiva',
  'Camping y Excursionismo',
  'Ciclismo',
  'Fitness',
  'Libros',
  'Películas y Series',
  'Música',
  'Juegos de Mesa',
  'Instrumentos Musicales',
  'Maquillaje',
  'Cuidado de la Piel',
  'Perfumes',
  'Cuidado del Cabello',
  'Higiene Personal',
  'Lavadoras y Secadoras',
  'Refrigeradores',
  'Hornos y Estufas',
  'Pequeños Electrodomésticos',
  'Juguetes para Niños',
  'Ropa Infantil',
  'Bebés',
  'Juegos Educativos',
];
